# Generated by Django 3.0.5 on 2021-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
